ExamExpert.WebApp/Controllers/ExamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ExamExpert.Bussinees.Interfaces;
using ExamExpert.Common.Models;
using ExamExpert.Common.ViewModels;
using ExamExpert.Data.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ExamExpert.WebApp.Controllers
{
    public class ExamController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IWiredHtmlAgilityService _wiredAPIService;
        private readonly IExamService _examService;

        public ExamController(UserManager<User> userManager, IWiredHtmlAgilityService wiredAPIService, IExamService examService)
        {
            _userManager = userManager;
            _wiredAPIService = wiredAPIService;
            _examService = examService;
        }

        // GET: Exam
        public ActionResult GenerateExam()
        {
            List<WiredTypingsListVM> wiredTypingsVM = new List<WiredTypingsListVM>();
            wiredTypingsVM = _wiredAPIService.GetLastFiveTypings();

            return View(wiredTypingsVM);
        }


        [HttpPost]
        public async Task<ActionResult> GenerateExam([FromBody]GenerateExamVM generateExamVM)
        {
            if (User.Identity.Name != null)
            {
                var teacherFromUsers = await _userManager.FindByNameAsync(User.Identity.Name);
                if (teacherFromUsers != null)
                {
                    var isSuccess = _examService.GenerateExam(generateExamVM, teacherFromUsers.Id);

                    if (isSuccess == true)
                    {
                        return Ok();
                    }
                }
            }
            return BadRequest();
        }


        public async Task<ActionResult> ListExams()
        {
            if (User.Identity.Name != null)
            {
                var user = await _userManager.FindByNameAsync(User.Identity.Name);

                if (user != null)
                {
                    //examListVM = _examService.GetAllExamsByTeacherId(user.Id);
                    var listExamModel = _examService.GetAllExamsByTeacherId(user.Id);

                    if (listExamModel != null)
                    {
                        var examListVM = new List<ExamListVM>();

                        for (int i = 0; i < listExamModel.Count; i++)
                        {
                            examListVM.Add(new ExamListVM
                            {
                                ExamOrderNumber = i + 1,
                                ExamPaper = new ExamModel()
                            });

                            examListVM[i].ExamPaper.ExamId = listExamModel[i].ExamId;
                            examListVM[i].ExamPaper.WiredTypingTitle = listExamModel[i].WiredTypingTitle;
                            examListVM[i].ExamPaper.WiredTypingContent = listExamModel[i].WiredTypingContent;
                            examListVM[i].ExamPaper.UserId = listExamModel[i].UserId;
                            examListVM[i].ExamPaper.CreateDate = listExamModel[i].CreateDate.Date;

                            for (int j = 0; j < listExamModel[i].Questions.Count; j++)
                            {
                                examListVM[i].ExamPaper.Questions.Add(new QuestionModel
                                {
                                    QuestionText = listExamModel[i].Questions[j].QuestionText,
                                    Choice_A = listExamModel[i].Questions[j].Choice_A,
                                    Choice_B = listExamModel[i].Questions[j].Choice_B,
                                    Choice_C = listExamModel[i].Questions[j].Choice_C,
                                    Choice_D = listExamModel[i].Questions[j].Choice_D,
                                    CorrectChoice = listExamModel[i].Questions[j].CorrectChoice
                                });
                            }

                        }
                        return View(examListVM);
                    }
                }
            }
            return BadRequest();
        }

        [HttpPost]
        public JsonResult DeleteExam(int examId)
        {
            string messageOfDeleteOperation = null;
            if (User.Identity.Name != null)
            {
                if (messageOfDeleteOperation != "failed")
                {
                    messageOfDeleteOperation = _examService.DeleteExamById(examId);
                    return Json(new { messageOfDeleteOperation = messageOfDeleteOperation });
                }
                else
                {
                    messageOfDeleteOperation = "Bir Hata Oluştu !";
                    return Json(new { messageOfDeleteOperation = messageOfDeleteOperation });
                }

            }
            messageOfDeleteOperation = "Kullanıcı Giriş Yapmamış !";
            return Json(new { messageOfDeleteOperation = messageOfDeleteOperation });
        }


        public ActionResult CheckExam(int examId) //examId will be sended from ListExams page.
        {
            var examPaper = new ExamPaperVM();
            var examModel = _examService.GetExamByIdForCheckingOperation(examId);

            examPaper.Exam.WiredTypingTitle = examModel.WiredTypingTitle;
            examPaper.Exam.WiredTypingContent = examModel.WiredTypingContent;

            for (int i = 0; i < examModel.Questions.Count; i++)
            {
                examPaper.Exam.Questions.Add(new QuestionModel
                {
                    QuestionId = examModel.Questions[i].QuestionId,
                    QuestionText = examModel.Questions[i].QuestionText,
                    Choice_A = examModel.Questions[i].Choice_A,
                    Choice_B = examModel.Questions[i].Choice_B,
                    Choice_C = examModel.Questions[i].Choice_C,
                    Choice_D = examModel.Questions[i].Choice_D,
                    CorrectChoice = examModel.Questions[i].CorrectChoice
                });
            }

            examPaper.Exam.UserId = examModel.UserId;
            examPaper.Exam.CreateDate = examModel.CreateDate;

            return View(examPaper);
        }

        [HttpPost]
        public JsonResult CheckExam([FromBody]List<CheckExamVM> answers) //examPaperDatas will be sended from CheckExam page.
        {
            if (User.Identity.Name != null)
            {
                return Json(new { results = _examService.CheckAnswersOfExam(answers) });
            }
            return Json(new { results = "error" });
        }
    }
}

ExamExpert.WebApp/Views/Exam/CheckExam.cshtml
@model ExamExpert.Common.ViewModels.ExamPaperVM

@{
    ViewData["Title"] = "Sınav Kontrolü";
}

<div class="row col-lg-10 col-md-10" id="div_FormLogin">
    <h1>@Model.Exam.WiredTypingTitle.ToUpper()</h1>
    <p>@Model.Exam.WiredTypingContent</p>

    <div class="row col-lg-10 col-md-10" id="btnGroup_RegisterLogin">
        <div class="col-lg-5 col-md-5">
            <div data-questionid="@Model.Exam.Questions[0].QuestionId" class="form-group question" style="margin-top: 30px">
                <div class="row">
                    1-) <p>@Model.Exam.Questions[0].QuestionText</p>
                </div>
                <div data-choiceValue="A" class="row" style="margin-top: 5px; border-style: solid">
                    A-)<a href="#"> @Model.Exam.Questions[0].Choice_A</a>
                </div>
                <div data-choiceValue="B" class="row" style="margin-top: 5px; border-style: solid">
                    B-)<a href="#"> @Model.Exam.Questions[0].Choice_B</a>
                </div>
                <div data-choiceValue="C" class="row" style="margin-top: 5px; border-style: solid">
                    C-)<a href="#"> @Model.Exam.Questions[0].Choice_C</a>
                </div>
                <div data-choiceValue="D" class="row" style="margin-top: 5px; border-style: solid">
                    D-)<a href="#"> @Model.Exam.Questions[0].Choice_D</a>
                </div>
            </div>
        </div>
        <div class="col-lg-5 col-md-5" style="margin-left: 50px">
            <div data-questionid="@Model.Exam.Questions[1].QuestionId" class="form-group question" style="margin-top: 30px">
                <div class="row">
                    2-) <p>@Model.Exam.Questions[1].QuestionText</p>
                </div>
                <div data-choiceValue="A" class="row" style="margin-top: 5px; border-style: solid">
                    A-)<a href="#"> @Model.Exam.Questions[1].Choice_A</a>
                </div>
                <div data-choiceValue="B" class="row" style="margin-top: 5px; border-style: solid">
                    B-)<a href="#"> @Model.Exam.Questions[1].Choice_B</a>
                </div>
                <div data-choiceValue="C" class="row" style="margin-top: 5px; border-style: solid">
                    C-)<a href="#"> @Model.Exam.Questions[1].Choice_C</a>
                </div>
                <div data-choiceValue="D" class="row" style="margin-top: 5px; border-style: solid">
                    D-)<a href="#"> @Model.Exam.Questions[1].Choice_D</a>
                </div>
            </div>
        </div>
    </div>

    <div class="row col-lg-10 col-md-10" id="btnGroup_RegisterLogin">
        <div class="col-lg-5 col-md-5">
            <div data-questionid="@Model.Exam.Questions[2].QuestionId" class="form-group question" style="margin-top: 30px">
                <div data-choiceValue="B" class="row">
                    3-) <p>@Model.Exam.Questions[2].QuestionText</p>
                </div>
                <div data-choiceValue="A" class="row" style="margin-top: 5px; border-style: solid">
                    A-)<a href="#"> @Model.Exam.Questions[2].Choice_A</a>
                </div>
                <div data-choiceValue="B" class="row" style="margin-top: 5px; border-style: solid">
                    B-)<a href="#"> @Model.Exam.Questions[2].Choice_B</a>
                </div>
                <div data-choiceValue="C" class="row" style="margin-top: 5px; border-style: solid">
                    C-)<a href="#"> @Model.Exam.Questions[2].Choice_C</a>
                </div>
                <div data-choiceValue="D" class="row" style="margin-top: 5px; border-style: solid">
                    D-)<a href="#"> @Model.Exam.Questions[2].Choice_D</a>
                </div>
            </div>
        </div>
        <div class="col-lg-5 col-md-5" style="margin-left: 50px">
            <div data-questionid="@Model.Exam.Questions[3].QuestionId" class="form-group question" style="margin-top: 30px">
                <div class="row">
                    4-) <p>@Model.Exam.Questions[3].QuestionText</p>
                </div>
                <div data-choiceValue="A" class="row" style="margin-top: 5px; border-style: solid">
                    A-)<a href="#"> @Model.Exam.Questions[3].Choice_A</a>
                </div>
                <div data-choiceValue="B" class="row" style="margin-top: 5px; border-style: solid">
                    B-)<a href="#"> @Model.Exam.Questions[3].Choice_B</a>
                </div>
                <div data-choiceValue="C" class="row" style="margin-top: 5px; border-style: solid">
                    C-)<a href="#"> @Model.Exam.Questions[3].Choice_C</a>
                </div>
                <div data-choiceValue="D" class="row" style="margin-top: 5px; border-style: solid">
                    D-)<a href="#"> @Model.Exam.Questions[3].Choice_D</a>
                </div>
            </div>
        </div>
    </div>


    <div class="row col-lg-12 col-md-12">
        <div class="col-lg-5 col-md-5"></div>
        <button id="checkExamButton" type="button" class="btn btn-primary col-lg-4 col-md-4">SINAVI TAMAMLA</button>
        <div class="col-lg-3 col-md-3"></div>
    </div>

    <div class="row col-lg-12 col-md-12"><hr /></div>

</div>


@section Scripts {
    <script type="text/javascript">
        $("#checkExamButton").on('click', function () {
            var questionsArray = [];

            var questions = $(".question");
            $.each(questions, function (i, item) {
                $.each($(item).children(), function (i, option) {
                    if ($(option).css("background-color") == "rgb(255, 255, 0)") {
                        var question = {};
                        question.QuestionId = $(option).parent().data("questionid");
                        question.Answer = $(option).data("choicevalue");
                        questionsArray.push(question);
                    }
                });
            });

            $.ajax({
                type: "POST",
                url: "/Exam/CheckExam",
                contentType: "application/json; charset=utf-8",
                dataType: "JSON",
                data: JSON.stringify(questionsArray),
                success: function (res) {
                    var answers = $("div").filter(function () {
                        return $(this).css("background-color") == "rgb(255, 255, 0)";
                    });

                    if (res.results != "error") {
                        $.each(res.results, function (i, item) {
                            if (item) {
                                $(answers[i]).css("background", "green");
                            } else {
                                $(answers[i]).css("background", "red");
                            }
                        });
                    }
                }
            });
        });

        $("a").on('click', function () {
            var childs = $(this).parent().parent().children();
            $.each(childs, function (i, item) {
                $(item).css("background", "white")
            })

            $(this).parent().css("background", "yellow");

        });
    </script>
}

ExamExpert.WebApp/Views/Exam/GenerateExam.cshtml
@model List<ExamExpert.Common.ViewModels.WiredTypingsListVM>

@{
    ViewData["Title"] = "Sınav Oluştur";
}

<div class="row col-lg-10 col-md-10" id="div_FormGenerateExam">
    <form class="col-lg-10 col-md-10" id="generateExamForm" asp-action="GenerateExam" asp-controller="Exam" method="post">

        <div class="row col-lg-10 col-md-10">
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="typingTitleButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Wiring yazısını seçiniz.
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    @foreach (var typing in Model)
                    {
                        <a class="dropdown-item typing" href="#">@typing.TypingTitle</a>
                    }
                </div>
            </div>
        </div>
        <div class="form-group">
            <textarea style="margin-top: 10px" class="form-control" id="typingContentTextarea" rows="7"></textarea>
        </div>
        <div class="form-group question" style="margin-top: 30px">
            <div class="row">
                Soru 1 - Başlık : <input name="questionText" />
            </div>
            <div class="row" style="margin-top: 5px">
                A-)<input name="choice_A" style="margin-right: 10px" /> B-)<input name="choice_B" />
            </div>
            <div class="row" style="margin-top: 5px">
                C-)<input name="choice_C" style="margin-right: 10px" /> D-)<input name="choice_D" />
            </div>
            <div class="dropdown" style="margin-top: 10px">
                Doğru Cevap : <button name="correctChoice" name="correctChoice" class="btn btn-secondary dropdown-toggle" type="button" id="question1Dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Doğru Cevabı Seçiniz.
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item choice1" href="#">A</a>
                    <a class="dropdown-item choice1" href="#">B</a>
                    <a class="dropdown-item choice1" href="#">C</a>
                    <a class="dropdown-item choice1" href="#">D</a>
                </div>
            </div>
        </div>

        <div class="form-group question" style="margin-top: 30px">
            <div class="row">
                Soru 2 - Başlık : <input name="questionText" />
            </div>
            <div class="row" style="margin-top: 5px">
                A-)<input name="choice_A" style="margin-right: 10px" /> B-)<input name="choice_B" />
            </div>
            <div class="row" style="margin-top: 5px">
                C-)<input name="choice_C" style="margin-right: 10px" /> D-)<input name="choice_D" />
            </div>
            <div class="dropdown" style="margin-top: 10px">
                Doğru Cevap : <button name="correctChoice" class="btn btn-secondary dropdown-toggle" type="button" id="question2Dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Doğru Cevabı Seçiniz.
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item choice2" href="#">A</a>
                    <a class="dropdown-item choice2" href="#">B</a>
                    <a class="dropdown-item choice2" href="#">C</a>
                    <a class="dropdown-item choice2" href="#">D</a>
                </div>
            </div>
        </div>

        <div class="form-group question" style="margin-top: 30px">
            <div class="row">
                Soru 3 - Başlık : <input name="questionText" />
            </div>
            <div class="row" style="margin-top: 5px">
                A-)<input name="choice_A" style="margin-right: 10px" /> B-)<input name="choice_B" />
            </div>
            <div class="row" style="margin-top: 5px">
                C-)<input name="choice_C" style="margin-right: 10px" /> D-)<input name="choice_D" />
            </div>
            <div class="dropdown" style="margin-top: 10px">
                Doğru Cevap : <button name="correctChoice" class="btn btn-secondary dropdown-toggle" type="button" id="question3Dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Doğru Cevabı Seçiniz.
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item choice3" href="#">A</a>
                    <a class="dropdown-item choice3" href="#">B</a>
                    <a class="dropdown-item choice3" href="#">C</a>
                    <a class="dropdown-item choice3" href="#">D</a>
                </div>
            </div>
        </div>

        <div class="form-group question" style="margin-top: 30px">
            <div class="row">
                Soru 4 - Başlık : <input name="questionText" />
            </div>
            <div class="row" style="margin-top: 5px">
                A-)<input name="choice_A" style="margin-right: 10px" /> B-)<input name="choice_B" />
            </div>
            <div class="row" style="margin-top: 5px">
                C-)<input name="choice_C" style="margin-right: 10px" /> D-)<input name="choice_D" />
            </div>
            <div class="dropdown" style="margin-top: 10px">
                Doğru Cevap : <button name="correctChoice" class="btn btn-secondary dropdown-toggle" type="button" id="question4Dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Doğru Cevabı Seçiniz.
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item choice4" href="#">A</a>
                    <a class="dropdown-item choice4" href="#">B</a>
                    <a class="dropdown-item choice4" href="#">C</a>
                    <a class="dropdown-item choice4" href="#">D</a>
                </div>
            </div>
        </div>

        <div class="form-group" style="margin-top: 30px">
            <div class="row col-lg-10 col-md-10">
                <button id="generateExamButton" type="button" class="btn btn-primary col-lg-5 col-md-5">Sınavı Oluştur</button>
                <div class="col-lg-3 col-md-3"></div>
                <a href="../../Home/Index" class="btn btn-primary col-lg-2 col-md-2">Vazgeç</a>
            </div>
        </div>
    </form>
</div>
<div class="row"></div>
@*<div class="row col-lg-10 col-md-10">
        <div class="col-lg-7 col-md-7"></div>
        <a href="../../Exam/ListExams" class="btn btn-primary col-lg-3 col-md-3">Sınav Listesini Görüntüle</a>
    </div>*@

@foreach (var typing in Model)
{
    <div style="display: none" id="@typing.TypingTitle.Replace(" ", "").Replace(":", "").Replace("#","").Replace(".","").Replace("´","").Replace("&","").Replace("-","").Replace("_","").Replace("|","").Replace("<","").Replace(">","")">@typing.TypingContent</div>
}

@section Scripts {
    <script type="text/javascript">
        $(".typing").on('click', function () {
            $("#typingTitleButton").html($(this).html())

            var typingContent = $("#" + $(this).html().replaceAll(" ", "").replaceAll(":", "")).html();
            $("#typingContentTextarea").html(typingContent);
        });

        $(".choice1").on('click', function () {
            $("#question1Dropdown").html($(this).html())
        });
        $(".choice2").on('click', function () {
            $("#question2Dropdown").html($(this).html())
        });
        $(".choice3").on('click', function () {
            $("#question3Dropdown").html($(this).html())
        });
        $(".choice4").on('click', function () {
            $("#question4Dropdown").html($(this).html())
        });

        $("#generateExamButton").on('click', function () {

            //var examData = new Array();
            //var exam = {};

            var exam = {};
            var data = new Array();
            var questions = $(".question");
            var state = 0;

            //exam.WiredTypingTitle = $("#typingTitleButton").html();
            //exam.WiredTypingContent = $("#typingContentTextarea").html();

            exam["WiredTypingTitle"] = $("#typingTitleButton").html();
            exam["WiredTypingContent"] = $("#typingContentTextarea").html();


            $.each(questions, function (i, item) {
                var question = {};
                question.QuestionText = $('input[name=questionText]')[i].value;
                question.Choice_A = $('input[name=choice_A]')[i].value;
                question.Choice_B = $('input[name=choice_B]')[i].value;
                question.Choice_C = $('input[name=choice_C]')[i].value;
                question.Choice_D = $('input[name=choice_D]')[i].value;
                question.CorrectChoice = $($('button[name=correctChoice]')[i]).html().trim();

                var q = question;
                if (q.Choice_A === "" || q.Choice_B === "" || q.Choice_C === "" || q.Choice_D === "" || q.CorrectChoice === "Doğru Cevabı Seçiniz." || exam["WiredTypingTitle"] === "Wiring yazısını seçiniz." || exam["WiredTypingContent"] === "") {
                    alert("Lütfen tüm alanları doldurunuz.");
                    state = 1;
                    return false;
                }

                data.push(question);
            });

            if (state != 1) {
                //exam["Questions"] = data;
                //exam.push(exam["Questions"]);

                //exam.Questions = data;
                //examData.push(exam);

                exam["Questions"] = data;
                $.ajax({
                    type: "POST",
                    url: "/Exam/GenerateExam",
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify({ Exam: exam }),
                    success: function (res) {
                        location.href = "/Exam/ListExams";
                    }
                });
            }
        });

    </script>
}

ExamExpert.WebApp/Views/Exam/ListExams.cshtml
@model IEnumerable<ExamExpert.Common.ViewModels.ExamListVM>

@{
    ViewData["Title"] = "Sınavlar";
}

<div class="row">
    <table class="table" id="logsList">
        <thead>
            <tr>
                <th>
                    #
                </th>
                <th>
                    Başlık
                </th>
                <th>
                    Tarih
                </th>
                <th>
                    İşlem
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.ExamOrderNumber
                    </td>
                    <td>
                        <a href="/Exam/CheckExam?examId=@item.ExamPaper.ExamId">@item.ExamPaper.WiredTypingTitle</a>
                    </td>
                    <td>
                        @item.ExamPaper.CreateDate.Date
                    </td>
                    <td>
                        <a href="#" class="deleteExam" data-examid="@item.ExamPaper.ExamId">Sil</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <br />
    <hr />

</div>


@section Scripts{
    <script type="text/javascript">
        $(".deleteExam").on('click', function () {
            var examId = $(this).data("examid");
            $.ajax({
                type: "POST",
                url: "/Exam/DeleteExam",
                dataType: "JSON",
                data: { examId: examId },
                success: function (res) {
                    alert(res.messageOfDeleteOperation);
                    location.reload();
                }
            });
        });
    </script>
}